import Alpine from 'alpinejs';
import {
    BadgeDollarSign,
    Bell,
    Braces,
    ChartNoAxesCombined,
    createIcons,
    DatabaseBackup,
    Files,
    Globe2,
    Images,
    Inbox,
    KeyRound,
    Languages,
    LayoutDashboard,
    ListFilter,
    LogOut,
    Mail,
    Menu,
    MessagesSquare,
    NotebookPen,
    Palette,
    PanelsTopLeft,
    PlugZap,
    RefreshCw,
    ScrollText,
    SearchCheck,
    ServerCog,
    Settings2,
    ShieldBan,
    ShieldCheck,
    Siren,
    SpellCheck2,
    SwatchBook,
    Tags,
    Type,
    UserRoundPen,
    Users,
    X,
} from 'lucide';

window.Alpine = Alpine;

Alpine.start();

createIcons({
    icons: {
        BadgeDollarSign,
        Bell,
        Braces,
        ChartNoAxesCombined,
        DatabaseBackup,
        Files,
        Globe2,
        Images,
        Inbox,
        KeyRound,
        Languages,
        LayoutDashboard,
        ListFilter,
        LogOut,
        Mail,
        Menu,
        MessagesSquare,
        NotebookPen,
        Palette,
        PanelsTopLeft,
        PlugZap,
        RefreshCw,
        ScrollText,
        SearchCheck,
        ServerCog,
        Settings2,
        ShieldBan,
        ShieldCheck,
        Siren,
        SpellCheck2,
        SwatchBook,
        Tags,
        Type,
        UserRoundPen,
        Users,
        X,
    },
});
