@props(['entry' => null, 'types', 'statuses', 'sources', 'canCreate', 'canUpdate'])
@php($editing = filled($entry))
@if (($editing && $canUpdate) || (! $editing && $canCreate))
<section aria-labelledby="blocked-entry-editor-title" class="rounded-lg border border-stone-200 bg-white p-5 shadow-sm">
    <div>
        <p class="text-xs font-extrabold uppercase text-teal-800">{{ $editing ? 'Edit rule' : 'Manual rule' }}</p>
        <h2 id="blocked-entry-editor-title" class="mt-1 text-lg font-extrabold text-stone-950">{{ $editing ? 'Update blocked-list entry' : 'Add reviewed entry' }}</h2>
        <p class="mt-1 text-sm text-stone-600">Detection and investigation stay in their own modules. This screen stores reviewed enforcement rules.</p>
    </div>
    <form method="POST" action="{{ $editing ? route('admin.blocked-lists.update', $entry) : route('admin.blocked-lists.store') }}" class="mt-5 space-y-4" x-data="{ busy: false }" x-on:submit="if (busy) $event.preventDefault(); busy = true" :aria-busy="busy">
        @csrf
        @if ($editing) @method('PUT') @endif
        <div class="grid gap-4 md:grid-cols-2">
            <div><label for="entry-type" class="text-sm font-bold text-stone-900">Entry type <span class="text-rose-700">*</span></label><select id="entry-type" name="entry_type" required aria-invalid="{{ $errors->has('entry_type') ? 'true' : 'false' }}" class="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20">@foreach ($types as $key => $label)<option value="{{ $key }}" @selected(old('entry_type', $entry?->entry_type ?? 'sender_email') === $key)>{{ $label }}</option>@endforeach</select>@error('entry_type')<p role="alert" class="mt-1 text-sm font-semibold text-rose-700">{{ $message }}</p>@enderror</div>
            <div><label for="entry-value" class="text-sm font-bold text-stone-900">Value or pattern <span class="text-rose-700">*</span></label><input id="entry-value" name="value" value="{{ old('value', $entry?->encrypted_normalized_value) }}" required maxlength="255" aria-describedby="entry-value-help" aria-invalid="{{ $errors->has('value') ? 'true' : 'false' }}" class="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20"><p id="entry-value-help" class="mt-1 text-xs text-stone-500">Safe examples: abuse@example.com, *@example.com, example.com, 198.51.100.4, 198.51.100.0/24.</p>@error('value')<p role="alert" class="mt-1 text-sm font-semibold text-rose-700">{{ $message }}</p>@enderror</div>
            <div><label for="entry-source" class="text-sm font-bold text-stone-900">Source</label><select id="entry-source" name="source" class="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3 text-sm">@foreach ($sources as $key => $label)<option value="{{ $key }}" @selected(old('source', $entry?->source ?? 'manual') === $key)>{{ $label }}</option>@endforeach</select></div>
            <div><label for="entry-status" class="text-sm font-bold text-stone-900">Status</label><select id="entry-status" name="status" class="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3 text-sm">@foreach ($statuses as $key => $label)<option value="{{ $key }}" @selected(old('status', $entry?->status ?? 'active') === $key)>{{ $label }}</option>@endforeach</select></div>
            <div><label for="entry-starts" class="text-sm font-bold text-stone-900">Starts at</label><input id="entry-starts" type="date" name="starts_at" value="{{ old('starts_at', $entry?->starts_at?->format('Y-m-d')) }}" class="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3 text-sm"></div>
            <div><label for="entry-expires" class="text-sm font-bold text-stone-900">Expires at</label><input id="entry-expires" type="date" name="expires_at" value="{{ old('expires_at', $entry?->expires_at?->format('Y-m-d')) }}" class="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3 text-sm">@error('expires_at')<p role="alert" class="mt-1 text-sm font-semibold text-rose-700">{{ $message }}</p>@enderror</div>
        </div>
        <div><label for="entry-case" class="text-sm font-bold text-stone-900">Related abuse case readiness</label><input id="entry-case" name="related_abuse_case" value="{{ old('related_abuse_case', $entry?->abuseReport?->case_reference) }}" placeholder="AB-260613-XXXXXXXXXXXX" class="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3 text-sm">@error('related_abuse_case')<p role="alert" class="mt-1 text-sm font-semibold text-rose-700">{{ $message }}</p>@enderror</div>
        <div><label for="entry-reason" class="text-sm font-bold text-stone-900">Reason <span class="text-rose-700">*</span></label><textarea id="entry-reason" name="reason" required rows="3" maxlength="2000" aria-invalid="{{ $errors->has('reason') ? 'true' : 'false' }}" class="mt-2 w-full rounded-lg border border-stone-300 px-3 py-2 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20">{{ old('reason', $entry?->reason) }}</textarea>@error('reason')<p role="alert" class="mt-1 text-sm font-semibold text-rose-700">{{ $message }}</p>@enderror</div>
        <div><label for="entry-notes" class="text-sm font-bold text-stone-900">Notes</label><textarea id="entry-notes" name="notes" rows="3" maxlength="2000" class="mt-2 w-full rounded-lg border border-stone-300 px-3 py-2 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20">{{ old('notes', $entry?->notes) }}</textarea></div>
        <x-blocked-lists.save-bar :editing="$editing" />
    </form>
</section>
@endif
