@props(['filters', 'types', 'statuses', 'sources', 'administrators'])
<form method="GET" action="{{ route('admin.blocked-lists.index') }}" class="rounded-lg border border-stone-200 bg-white p-4 shadow-sm">
    <input type="hidden" name="group" value="{{ $filters['group'] }}">
    <div class="grid gap-3 md:grid-cols-6 xl:grid-cols-7">
        <div class="md:col-span-2"><label for="blocked-q" class="text-xs font-bold text-stone-600">Search</label><input id="blocked-q" name="q" value="{{ $filters['q'] }}" class="mt-1 min-h-10 w-full rounded-lg border border-stone-300 px-3 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20"></div>
        <div><label for="blocked-type" class="text-xs font-bold text-stone-600">Type</label><select id="blocked-type" name="entry_type" class="mt-1 min-h-10 w-full rounded-lg border border-stone-300 px-3 text-sm"><option value="all">All</option>@foreach ($types as $key => $label)<option value="{{ $key }}" @selected($filters['entry_type'] === $key)>{{ $label }}</option>@endforeach</select></div>
        <div><label for="blocked-status" class="text-xs font-bold text-stone-600">Status</label><select id="blocked-status" name="status" class="mt-1 min-h-10 w-full rounded-lg border border-stone-300 px-3 text-sm"><option value="all">All</option>@foreach ($statuses as $key => $label)<option value="{{ $key }}" @selected($filters['status'] === $key)>{{ $label }}</option>@endforeach</select></div>
        <div><label for="blocked-source" class="text-xs font-bold text-stone-600">Source</label><select id="blocked-source" name="source" class="mt-1 min-h-10 w-full rounded-lg border border-stone-300 px-3 text-sm"><option value="all">All</option>@foreach ($sources as $key => $label)<option value="{{ $key }}" @selected($filters['source'] === $key)>{{ $label }}</option>@endforeach</select></div>
        <div><label for="blocked-expiry" class="text-xs font-bold text-stone-600">Expiry</label><select id="blocked-expiry" name="expiry" class="mt-1 min-h-10 w-full rounded-lg border border-stone-300 px-3 text-sm"><option value="all">All</option><option value="expires" @selected($filters['expiry'] === 'expires')>Has expiry</option><option value="expired" @selected($filters['expiry'] === 'expired')>Expired</option></select></div>
        <div><label for="blocked-created-by" class="text-xs font-bold text-stone-600">Created by</label><select id="blocked-created-by" name="created_by" class="mt-1 min-h-10 w-full rounded-lg border border-stone-300 px-3 text-sm"><option value="">All</option>@foreach ($administrators as $administrator)<option value="{{ $administrator->id }}" @selected((string) $filters['created_by'] === (string) $administrator->id)>{{ $administrator->name }} ({{ $administrator->role }})</option>@endforeach</select></div>
    </div>
    <div class="mt-3 flex flex-wrap gap-3"><button class="inline-flex min-h-10 items-center rounded-lg bg-teal-700 px-4 text-sm font-extrabold text-white">Apply filters</button><a href="{{ route('admin.blocked-lists.index', ['group' => $filters['group']]) }}" class="inline-flex min-h-10 items-center rounded-lg border border-stone-300 px-4 text-sm font-extrabold text-stone-700">Reset</a></div>
</form>
