@props(['filters', 'statuses', 'types', 'domains'])
<form method="GET" action="{{ route('admin.mailbox-operations.index') }}" class="rounded-lg border border-stone-200 bg-white p-4 shadow-sm">
    <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-7">
        <label class="grid gap-2 xl:col-span-2"><span class="text-xs font-extrabold uppercase text-stone-500">Email search</span><input type="search" name="q" value="{{ $filters['q'] }}" placeholder="inbox@example.com" class="min-h-11 rounded-md border border-stone-300 px-3 text-sm font-bold text-stone-900 focus:border-teal-600 focus:outline-none focus:ring-4 focus:ring-teal-600/20"></label>
        <label class="grid gap-2"><span class="text-xs font-extrabold uppercase text-stone-500">Status</span><select name="status" class="min-h-11 rounded-md border border-stone-300 bg-white px-3 text-sm font-bold text-stone-900"><option value="all">All</option>@foreach($statuses as $value => $label)<option value="{{ $value }}" @selected($filters['status'] === $value)>{{ $label }}</option>@endforeach</select></label>
        <label class="grid gap-2"><span class="text-xs font-extrabold uppercase text-stone-500">Domain</span><select name="domain_id" class="min-h-11 rounded-md border border-stone-300 bg-white px-3 text-sm font-bold text-stone-900"><option value="all">All</option>@foreach($domains as $domain)<option value="{{ $domain->id }}" @selected($filters['domain_id'] === (string)$domain->id)>{{ $domain->domain_name }}</option>@endforeach</select></label>
        <label class="grid gap-2"><span class="text-xs font-extrabold uppercase text-stone-500">Owner</span><select name="owner" class="min-h-11 rounded-md border border-stone-300 bg-white px-3 text-sm font-bold text-stone-900"><option value="all">All</option><option value="guest" @selected($filters['owner']==='guest')>Guest</option><option value="registered" @selected($filters['owner']==='registered')>Registered</option></select></label>
        <label class="grid gap-2"><span class="text-xs font-extrabold uppercase text-stone-500">Type</span><select name="mailbox_type" class="min-h-11 rounded-md border border-stone-300 bg-white px-3 text-sm font-bold text-stone-900"><option value="all">All</option>@foreach($types as $value => $label)<option value="{{ $value }}" @selected($filters['mailbox_type']===$value)>{{ $label }}</option>@endforeach</select></label>
        <label class="grid gap-2"><span class="text-xs font-extrabold uppercase text-stone-500">Created</span><select name="created" class="min-h-11 rounded-md border border-stone-300 bg-white px-3 text-sm font-bold text-stone-900"><option value="all">Any time</option><option value="today" @selected($filters['created']==='today')>Today</option><option value="week" @selected($filters['created']==='week')>Last 7 days</option><option value="month" @selected($filters['created']==='month')>Last 30 days</option></select></label>
    </div>
    <div class="mt-4 flex flex-wrap gap-2"><button class="inline-flex min-h-10 items-center rounded-md bg-stone-950 px-4 text-sm font-extrabold text-white focus:outline-none focus:ring-4 focus:ring-teal-600/20">Apply filters</button><a href="{{ route('admin.mailbox-operations.index') }}" class="inline-flex min-h-10 items-center rounded-md border border-stone-300 bg-white px-4 text-sm font-extrabold text-stone-700">Reset</a></div>
</form>
