@props(['rules', 'canUpdate' => false])
<x-admin.card title="Lifetime and capacity" description="Safe limits protect shared-hosting resources while preserving predictable inbox behavior.">
    <x-mailbox.rule-row name="guest_lifetime_minutes" label="Guest mailbox lifetime" description="Default lifetime for anonymous temporary inboxes." :value="$rules->guest_lifetime_minutes" :min="15" :max="43200" suffix="minutes" :can-update="$canUpdate" />
    <x-mailbox.rule-row name="registered_lifetime_minutes" label="Registered mailbox lifetime" description="Lifetime for inboxes attached to registered users." :value="$rules->registered_lifetime_minutes" :min="60" :max="525600" suffix="minutes" :can-update="$canUpdate" />
    <x-mailbox.rule-row name="premium_lifetime_minutes" label="Premium lifetime readiness" description="Stored for future Plans integration; no plan enforcement occurs here." :value="$rules->premium_lifetime_minutes" :min="60" :max="525600" suffix="minutes" :can-update="$canUpdate" />
    <x-mailbox.rule-row name="maximum_active_mailboxes" label="Maximum active mailboxes readiness" description="Capacity hook for future account and plan enforcement." :value="$rules->maximum_active_mailboxes" :min="1" :max="1000" suffix="mailboxes" :can-update="$canUpdate" />
    <x-mailbox.rule-row name="maximum_messages_per_inbox" label="Maximum messages per inbox" description="Upper bound used by inbound processing and retention decisions." :value="$rules->maximum_messages_per_inbox" :min="1" :max="10000" suffix="messages" :can-update="$canUpdate" />
    <x-mailbox.rule-row name="maximum_message_size_kb" label="Maximum message size" description="Messages above this size should be rejected by the inbound processor." :value="$rules->maximum_message_size_kb" :min="64" :max="102400" suffix="KB" :can-update="$canUpdate" />
    <x-mailbox.rule-row name="expired_cleanup_delay_hours" label="Expired cleanup delay" description="Grace period before an expired mailbox becomes eligible for cleanup." :value="$rules->expired_cleanup_delay_hours" :min="1" :max="8760" suffix="hours" :can-update="$canUpdate" />
    <x-mailbox.rule-row name="inbox_refresh_rate_limit" label="Inbox refresh interval readiness" description="Minimum client refresh interval for future public inbox delivery." :value="$rules->inbox_refresh_rate_limit" :min="5" :max="3600" suffix="seconds" :can-update="$canUpdate" />
    <x-mailbox.rule-row name="random_alias_length" label="Random alias length" description="Length used by future generated mailbox aliases." :value="$rules->random_alias_length" :min="6" :max="64" suffix="characters" :can-update="$canUpdate" />

    <div class="grid gap-4 border-t border-stone-200 pt-5 md:grid-cols-2">
        <label class="grid gap-2 text-sm font-extrabold text-stone-950">Attachment policy<select name="attachment_policy" @disabled(! $canUpdate) class="min-h-11 rounded-md border border-stone-300 bg-white px-3 focus:border-teal-600 focus:outline-none focus:ring-4 focus:ring-teal-600/20"><option value="disabled" @selected(old('attachment_policy', $rules->attachment_policy) === 'disabled')>Disabled</option><option value="metadata_only" @selected(old('attachment_policy', $rules->attachment_policy) === 'metadata_only')>Metadata only readiness</option></select><span class="text-sm font-normal text-stone-600">Downloads and quarantine remain disabled.</span></label>
        <label class="grid gap-2 text-sm font-extrabold text-stone-950">Random alias format<select name="random_alias_format" @disabled(! $canUpdate) class="min-h-11 rounded-md border border-stone-300 bg-white px-3 focus:border-teal-600 focus:outline-none focus:ring-4 focus:ring-teal-600/20"><option value="alphanumeric" @selected(old('random_alias_format', $rules->random_alias_format) === 'alphanumeric')>Alphanumeric</option><option value="letters" @selected(old('random_alias_format', $rules->random_alias_format) === 'letters')>Letters only</option><option value="words" @selected(old('random_alias_format', $rules->random_alias_format) === 'words')>Readable words readiness</option></select></label>
    </div>
    <label class="mt-5 flex gap-3 rounded-md border border-stone-200 bg-stone-50 p-4"><input type="checkbox" name="auto_delete_expired" value="1" @checked(old('auto_delete_expired', $rules->auto_delete_expired)) @disabled(! $canUpdate) class="mt-0.5 size-4 rounded border-stone-300 text-teal-700 focus:ring-teal-600/20"><span><span class="block text-sm font-extrabold text-stone-950">Automatically delete eligible expired mailboxes</span><span class="mt-1 block text-sm text-stone-600">Only expired records older than the cleanup delay are eligible. Active mailboxes are excluded.</span></span></label>
</x-admin.card>
