@props(['report', 'canExecute'])
@if ($canExecute)
<section class="rounded-lg border border-stone-200 bg-white p-5 shadow-sm" x-data="{ action: '{{ old('operational_action') }}', busy: false }">
    <h2 class="text-base font-extrabold text-stone-950">Operational action</h2><p class="mt-1 text-sm text-stone-600">Use the owning module action after human review. Nothing runs automatically.</p><div class="mt-4"><x-abuse.operational-action-warning /></div>
    <form method="POST" action="{{ route('admin.abuse-reports.operational-actions.execute', $report) }}" class="mt-4 space-y-3" x-on:submit="if (busy) $event.preventDefault(); busy = true" :aria-busy="busy">@csrf
        <div><label for="operational-action" class="text-sm font-bold text-stone-900">Action <span class="text-rose-700">*</span></label><select id="operational-action" name="operational_action" x-model="action" required class="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20"><option value="">Select action</option><option value="lock_mailbox">Lock linked mailbox</option><option value="expire_mailbox">Expire linked mailbox</option><option value="suspend_user">Suspend linked user</option><option value="trash_comment">Trash linked comment</option><option value="block_sender_email">Block sender email</option><option value="block_sender_domain">Block sender domain</option><option value="block_recipient_email">Block recipient email</option><option value="block_recipient_domain">Block recipient domain</option><option value="block_ip_hash">Block IP/hash readiness</option></select></div>
        <div x-cloak x-show="action.startsWith('block_')"><label for="block-value" class="text-sm font-bold text-stone-900">Block value</label><input id="block-value" name="block_value" value="{{ old('block_value') }}" maxlength="255" class="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20"></div>
        <div><label for="operational-reason" class="text-sm font-bold text-stone-900">Reason <span class="text-rose-700">*</span></label><textarea id="operational-reason" name="reason" required minlength="10" maxlength="2000" rows="3" class="mt-2 w-full rounded-lg border border-stone-300 px-3 py-2 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20">{{ old('reason') }}</textarea></div>
        <label class="flex items-start gap-3 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3"><input type="checkbox" name="confirm_action" value="1" required class="mt-0.5 size-4 rounded border-rose-400 text-rose-700 focus:ring-rose-600"><span class="text-sm font-bold text-rose-950">I reviewed the case and confirm this high-impact action.</span></label>
        <button :disabled="busy" class="inline-flex min-h-11 items-center rounded-lg bg-rose-700 px-4 text-sm font-extrabold text-white focus:outline-none focus:ring-4 focus:ring-rose-600/25 disabled:opacity-60"><span x-show="!busy">Execute confirmed action</span><span x-cloak x-show="busy">Executing…</span></button>
    </form>
</section>
@endif
