@props(['report', 'readiness', 'canResolve'])
@if ($canResolve && !in_array($report->status, ['resolved', 'rejected', 'archived'], true))
<section class="rounded-lg border border-stone-200 bg-white p-5 shadow-sm" x-data="{ tab: 'resolve', busy: false }">
    <div><h2 class="text-base font-extrabold text-stone-950">Resolution decision</h2><p class="mt-1 text-sm text-stone-600">Record the reviewed outcome and a mandatory reason. Operational changes remain separate and explicitly confirmed.</p></div>
    <div class="mt-4 inline-flex rounded-lg bg-stone-100 p-1" role="tablist"><button type="button" role="tab" :aria-selected="tab === 'resolve'" @click="tab='resolve'" class="min-h-9 rounded-md px-3 text-sm font-extrabold" :class="tab === 'resolve' ? 'bg-white text-stone-950 shadow-sm' : 'text-stone-600'">Resolve</button><button type="button" role="tab" :aria-selected="tab === 'reject'" @click="tab='reject'" class="min-h-9 rounded-md px-3 text-sm font-extrabold" :class="tab === 'reject' ? 'bg-white text-stone-950 shadow-sm' : 'text-stone-600'">Reject invalid</button></div>
    <form x-show="tab === 'resolve'" method="POST" action="{{ route('admin.abuse-reports.resolve', $report) }}" class="mt-4 space-y-4" x-on:submit="if (busy) $event.preventDefault(); busy = true" :aria-busy="busy">@csrf
        <div><label for="resolution-outcome" class="text-sm font-bold text-stone-900">Outcome <span class="text-rose-700">*</span></label><select id="resolution-outcome" name="resolution_outcome" required class="mt-2 min-h-11 w-full rounded-lg border border-stone-300 px-3 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20">@foreach (['no_action','warning_issued','mailbox_locked','mailbox_expired','user_suspended','sender_or_domain_blocked','content_removed_readiness','referred_for_legal_review'] as $outcome)<option value="{{ $outcome }}" @selected(old('resolution_outcome') === $outcome)>{{ str($outcome)->replace('_', ' ')->headline() }}</option>@endforeach</select></div>
        <div><label for="resolution-reason" class="text-sm font-bold text-stone-900">Resolution reason <span class="text-rose-700">*</span></label><textarea id="resolution-reason" name="resolution_reason" required minlength="10" maxlength="5000" rows="4" aria-invalid="{{ $errors->has('resolution_reason') ? 'true' : 'false' }}" class="mt-2 w-full rounded-lg border border-stone-300 px-3 py-2 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20">{{ old('resolution_reason') }}</textarea></div>
        <div><label for="resolution-summary" class="text-sm font-bold text-stone-900">Public-safe summary</label><textarea id="resolution-summary" name="resolution_summary" maxlength="2000" rows="3" class="mt-2 w-full rounded-lg border border-stone-300 px-3 py-2 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20">{{ old('resolution_summary') }}</textarea></div>
        <x-abuse.reporter-response-panel :report="$report" :readiness="$readiness" prefix="resolution" />
        <label class="flex items-start gap-3"><input type="checkbox" name="confirm_resolution" value="1" required class="mt-0.5 size-4 rounded border-stone-400 text-teal-700 focus:ring-teal-600"><span class="text-sm font-bold text-stone-800">I confirm this reviewed resolution.</span></label><button :disabled="busy" class="inline-flex min-h-11 items-center rounded-lg bg-teal-700 px-4 text-sm font-extrabold text-white focus:outline-none focus:ring-4 focus:ring-teal-600/25 disabled:opacity-60">Resolve case</button>
    </form>
    <form x-cloak x-show="tab === 'reject'" method="POST" action="{{ route('admin.abuse-reports.reject', $report) }}" class="mt-4 space-y-4">@csrf<div><label for="rejection-reason" class="text-sm font-bold text-stone-900">Rejection reason <span class="text-rose-700">*</span></label><textarea id="rejection-reason" name="resolution_reason" required minlength="10" maxlength="5000" rows="4" class="mt-2 w-full rounded-lg border border-stone-300 px-3 py-2 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20">{{ old('resolution_reason') }}</textarea></div><div><label for="rejection-summary" class="text-sm font-bold text-stone-900">Public-safe summary</label><textarea id="rejection-summary" name="resolution_summary" maxlength="2000" rows="3" class="mt-2 w-full rounded-lg border border-stone-300 px-3 py-2 text-sm focus:border-teal-700 focus:outline-none focus:ring-4 focus:ring-teal-600/20">{{ old('resolution_summary') }}</textarea></div><x-abuse.reporter-response-panel :report="$report" :readiness="$readiness" prefix="rejection" /><label class="flex items-start gap-3"><input type="checkbox" name="confirm_rejection" value="1" required class="mt-0.5 size-4 rounded border-rose-400 text-rose-700 focus:ring-rose-600"><span class="text-sm font-bold text-rose-900">I confirm this report is invalid or unsupported.</span></label><button class="inline-flex min-h-11 items-center rounded-lg bg-rose-700 px-4 text-sm font-extrabold text-white focus:outline-none focus:ring-4 focus:ring-rose-600/25">Reject case</button></form>
</section>
@endif
