<x-admin.layout title="Create Mailbox" :user="$adminUser">
    <x-admin.page-header eyebrow="Mailbox Operations" title="Create Mailbox" description="Create lifecycle readiness on an active, public, DNS-ready receiving domain." />

    <x-admin.card title="Mailbox identity" description="Plans, reservations, claiming, and automated TTL policies are intentionally deferred.">
        @if($errors->any())<div class="mb-5 rounded-lg border border-red-200 bg-red-50 p-4 text-red-950" role="alert" aria-labelledby="mailbox-errors"><p id="mailbox-errors" class="text-sm font-extrabold">Mailbox settings need attention</p><ul class="mt-2 list-inside list-disc space-y-1 text-sm">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

        @if($domains->isEmpty())
            <x-admin.alert variant="warning" title="No usable receiving domain">Activate a public domain and complete DNS readiness before creating mailboxes.</x-admin.alert>
        @else
            <form method="POST" action="{{ route('admin.mailbox-operations.store') }}" class="space-y-6" x-data="{ submitting: false, mailboxType: @js(old('mailbox_type', 'guest')) }" x-on:submit="if (submitting) { $event.preventDefault(); return; } submitting = true" x-bind:aria-busy="submitting.toString()" x-bind:class="{ 'pointer-events-none opacity-75': submitting }">
                @csrf
                <div class="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(260px,0.7fr)]">
                    <label class="grid gap-2"><span class="text-sm font-bold text-stone-700">Local part <span class="text-red-700" aria-hidden="true">*</span></span><input name="local_part" value="{{ old('local_part') }}" required autocomplete="off" autocapitalize="none" spellcheck="false" placeholder="temporary-inbox" aria-invalid="{{ $errors->has('local_part') ? 'true' : 'false' }}" aria-describedby="{{ $errors->has('local_part') ? 'local-part-error' : 'local-part-help' }}" class="min-h-11 rounded-md border border-stone-300 px-3 text-sm font-bold text-stone-900 focus:border-teal-600 focus:outline-none focus:ring-4 focus:ring-teal-600/20"><span id="local-part-help" class="text-xs text-stone-500">Letters, numbers, dots, underscores, and hyphens.</span>@error('local_part')<span id="local-part-error" class="text-xs font-bold text-red-700" role="alert">{{ $message }}</span>@enderror</label>
                    <label class="grid gap-2"><span class="text-sm font-bold text-stone-700">Receiving domain <span class="text-red-700" aria-hidden="true">*</span></span><select name="domain_id" required aria-invalid="{{ $errors->has('domain_id') ? 'true' : 'false' }}" class="min-h-11 rounded-md border border-stone-300 bg-white px-3 text-sm font-bold text-stone-900 focus:border-teal-600 focus:outline-none focus:ring-4 focus:ring-teal-600/20"><option value="">Select domain</option>@foreach($domains as $domain)<option value="{{ $domain->id }}" @selected((string)old('domain_id')===(string)$domain->id)>{{ $domain->domain_name }}</option>@endforeach</select>@error('domain_id')<span class="text-xs font-bold text-red-700" role="alert">{{ $message }}</span>@enderror</label>
                </div>
                <div class="grid gap-4 lg:grid-cols-3">
                    <label class="grid gap-2"><span class="text-sm font-bold text-stone-700">Mailbox type <span class="text-red-700" aria-hidden="true">*</span></span><select name="mailbox_type" x-model="mailboxType" class="min-h-11 rounded-md border border-stone-300 bg-white px-3 text-sm font-bold text-stone-900">@foreach($types as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></label>
                    <label class="grid gap-2"><span class="text-sm font-bold text-stone-700">Registered owner</span><select name="user_id" x-bind:required="mailboxType === 'registered'" class="min-h-11 rounded-md border border-stone-300 bg-white px-3 text-sm font-bold text-stone-900"><option value="">Guest / unassigned</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)old('user_id')===(string)$user->id)>{{ $user->email }}</option>@endforeach</select>@error('user_id')<span class="text-xs font-bold text-red-700" role="alert">{{ $message }}</span>@enderror</label>
                    <label class="grid gap-2"><span class="text-sm font-bold text-stone-700">Locale readiness</span><select name="locale_id" class="min-h-11 rounded-md border border-stone-300 bg-white px-3 text-sm font-bold text-stone-900"><option value="">Not assigned</option>@foreach($locales as $locale)<option value="{{ $locale->id }}" @selected((string)old('locale_id')===(string)$locale->id)>{{ $locale->locale }} · {{ $locale->language_name }}</option>@endforeach</select></label>
                </div>
                <label class="grid max-w-md gap-2"><span class="text-sm font-bold text-stone-700">Expires at</span><input type="datetime-local" name="expires_at" value="{{ old('expires_at') }}" class="min-h-11 rounded-md border border-stone-300 px-3 text-sm font-bold text-stone-900 focus:border-teal-600 focus:outline-none focus:ring-4 focus:ring-teal-600/20">@error('expires_at')<span class="text-xs font-bold text-red-700" role="alert">{{ $message }}</span>@enderror</label>
                <div class="flex justify-end border-t border-stone-200 pt-5"><button x-bind:disabled="submitting" class="inline-flex min-h-11 items-center rounded-md bg-stone-950 px-4 text-sm font-extrabold text-white disabled:bg-stone-400"><span x-show="!submitting">Create mailbox</span><span x-cloak x-show="submitting">Creating...</span></button></div>
            </form>
        @endif
    </x-admin.card>
</x-admin.layout>
